<?php

namespace ApiLens;

use ApiLens\Models\Endpoint;

/**
 * Converts Endpoint collection to OpenAPI 3.1.0 specification.
 * Improvement: Supports OpenAPI 3.1.0 (vs 3.0.0 in competitor).
 * Includes response schema, examples, and richer type information.
 */
class ApiLensToOpenApi
{
    /** @var array<string, mixed> */
    private array $openApi;

    /**
     * Build OpenAPI document from endpoints.
     *
     * @param Endpoint[] $endpoints
     * @return $this
     */
    public function openApi(array $endpoints): self
    {
        $this->openApi = [
            'openapi' => config('api-lens.open_api.version', '3.1.0'),
            'info' => [
                'title'       => config('api-lens.open_api.title', 'API Documentation'),
                'description' => config('api-lens.open_api.description', 'Auto-generated by API Lens'),
                'version'     => config('api-lens.open_api.document_version', '1.0.0'),
                'license'     => [
                    'name' => config('api-lens.open_api.license', 'Apache 2.0'),
                    'url'  => config('api-lens.open_api.license_url', 'https://www.apache.org/licenses/LICENSE-2.0.html'),
                ],
            ],
            'servers' => [
                ['url' => config('api-lens.open_api.server_url', config('app.url', 'http://localhost'))],
            ],
        ];

        $this->buildPaths($endpoints);
        $this->buildTags($endpoints);
        $this->buildSecuritySchemes();

        return $this;
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return $this->openApi;
    }

    public function toJson(): string
    {
        return json_encode(
            $this->openApi,
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
    }

    /**
     * @param Endpoint[] $endpoints
     */
    private function buildPaths(array $endpoints): void
    {
        $this->openApi['paths'] = [];

        $deleteWithBody = config('api-lens.open_api.delete_with_body', false);
        $excludeHttpMethods = array_map(
            fn($item) => strtolower($item),
            config('api-lens.open_api.exclude_http_methods', [])
        );

        foreach ($endpoints as $endpoint) {
            $httpMethod = strtolower($endpoint->getHttpMethod());

            if (in_array($httpMethod, $excludeHttpMethods)) {
                continue;
            }

            $uriPath = '/' . ltrim($endpoint->getUri(), '/');
            $isGet = $httpMethod === 'get';
            $isPost = $httpMethod === 'post';
            $isPut = $httpMethod === 'put';
            $isPatch = $httpMethod === 'patch';
            $isDelete = $httpMethod === 'delete';

            $operation = [];

            // Summary and Description
            if ($endpoint->getSummary()) {
                $operation['summary'] = $endpoint->getSummary();
            }

            if ($endpoint->getDocBlock()) {
                $operation['description'] = $endpoint->getDocBlock();
            }

            // Tags
            $tags = $endpoint->getTags();
            if (!empty($tags)) {
                $operation['tags'] = $tags;
            } elseif ($endpoint->getController()) {
                $operation['tags'] = [str_replace('Controller', '', $endpoint->getController())];
            }

            // Deprecated
            if ($endpoint->isDeprecated()) {
                $operation['deprecated'] = true;
            }

            // Operation ID
            $operation['operationId'] = $this->generateOperationId($endpoint);

            // Parameters (path + query)
            $operation['parameters'] = [];

            foreach ($endpoint->getPathParameters() as $parameter => $rule) {
                $operation['parameters'][] = $this->makePathParameter($parameter, $rule);
            }

            // Query parameters for GET
            if ($isGet) {
                foreach ($endpoint->getRules() as $attribute => $rules) {
                    foreach ($rules as $rule) {
                        $operation['parameters'][] = $this->makeQueryParameter($attribute, $rule);
                    }
                }
            }

            // Request body for POST, PUT, PATCH
            $requestHasFile = $this->hasFileRule($endpoint->getRules());
            $contentType = $requestHasFile ? 'multipart/form-data' : 'application/json';

            if ($isPost || $isPut || $isPatch || ($isDelete && $deleteWithBody)) {
                $operation['requestBody'] = $this->buildRequestBody($endpoint, $contentType);
            }

            // Responses
            $operation['responses'] = $this->buildResponses($endpoint);

            // Security
            if ($endpoint->getAuthType()) {
                $operation['security'] = [$this->getSecurityRequirement($endpoint->getAuthType())];
            }

            $this->openApi['paths'][$uriPath][$httpMethod] = $operation;
        }
    }

    /**
     * Build tags section from unique endpoint tags.
     *
     * @param Endpoint[] $endpoints
     */
    private function buildTags(array $endpoints): void
    {
        $tags = [];

        foreach ($endpoints as $endpoint) {
            $endpointTags = $endpoint->getTags();
            if (empty($endpointTags) && $endpoint->getController()) {
                $endpointTags = [str_replace('Controller', '', $endpoint->getController())];
            }

            foreach ($endpointTags as $tag) {
                if (!isset($tags[$tag])) {
                    $tags[$tag] = ['name' => $tag];
                }
            }
        }

        if (!empty($tags)) {
            $this->openApi['tags'] = array_values($tags);
        }
    }

    private function generateOperationId(Endpoint $endpoint): string
    {
        $method = strtolower($endpoint->getHttpMethod());
        $uri = str_replace(['/', '{', '}', '?'], ['_', '', '', ''], $endpoint->getUri());
        return $method . '_' . $uri;
    }

    /**
     * @param string[] $rule
     * @return array<string, mixed>
     */
    private function makePathParameter(string $attribute, array $rule): array
    {
        $ruleStr = implode('|', $rule);

        return [
            'name'        => $attribute,
            'description' => $ruleStr,
            'in'          => 'path',
            'required'    => !str_contains($ruleStr, 'nullable'),
            'schema'      => ['type' => $this->getSchemaType($ruleStr)],
        ];
    }

    private function makeQueryParameter(string $attribute, string $rule): array
    {
        return [
            'name'        => $attribute,
            'description' => $rule,
            'in'          => 'query',
            'required'    => str_contains($rule, 'required'),
            'schema'      => ['type' => $this->getSchemaType($rule)],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function buildRequestBody(Endpoint $endpoint, string $contentType): array
    {
        $properties = [];

        foreach ($endpoint->getRules() as $attribute => $rules) {
            $ruleStr = implode('|', $rules);
            $properties[$attribute] = [
                'type'     => $this->getSchemaType($ruleStr),
                'nullable' => str_contains($ruleStr, 'nullable'),
            ];

            if ($this->isFileRule($ruleStr)) {
                $properties[$attribute]['format'] = 'binary';
            }

            // Add example value if available
            $example = $endpoint->getExampleRequest()[$attribute] ?? null;
            if ($example !== null) {
                $properties[$attribute]['example'] = $example;
            }
        }

        $required = [];
        foreach ($endpoint->getRules() as $attribute => $rules) {
            $ruleStr = implode('|', $rules);
            if (str_contains($ruleStr, 'required')) {
                $required[] = $attribute;
            }
        }

        $schema = [
            'type'       => 'object',
            'properties' => $properties,
        ];

        if (!empty($required)) {
            $schema['required'] = $required;
        }

        return [
            'description' => 'Request body',
            'required'    => !empty($required),
            'content'     => [
                $contentType => [
                    'schema' => $schema,
                ],
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function buildResponses(Endpoint $endpoint): array
    {
        $docResponses = $endpoint->getResponses();
        $configResponses = config('api-lens.open_api.responses', []);

        if (empty($docResponses)) {
            return $configResponses;
        }

        $responses = [];
        foreach ($docResponses as $code) {
            $responses[$code] = $configResponses[$code] ?? $configResponses['default'] ?? [
                'description' => $this->getResponseDescription($code),
            ];
        }

        // Add response schema if available
        $responseSchema = $endpoint->getResponseSchema();
        if (!empty($responseSchema) && isset($responses['200'])) {
            $responses['200']['content'] = [
                'application/json' => [
                    'schema' => [
                        'type'       => 'object',
                        'properties' => $this->convertSchemaToOpenApi($responseSchema),
                    ],
                ],
            ];
        }

        return $responses;
    }

    private function getResponseDescription(string $code): string
    {
        return match ($code) {
            '200' => 'Successful operation',
            '201' => 'Resource created',
            '204' => 'No content',
            '400' => 'Bad request',
            '401' => 'Unauthorized',
            '403' => 'Forbidden',
            '404' => 'Not found',
            '405' => 'Method not allowed',
            '409' => 'Conflict',
            '422' => 'Validation error',
            '429' => 'Too many requests',
            '500' => 'Internal server error',
            '503' => 'Service unavailable',
            default => 'Response',
        };
    }

    /**
     * @param array<string, mixed> $schema
     * @return array<string, mixed>
     */
    private function convertSchemaToOpenApi(array $schema): array
    {
        $properties = [];

        foreach ($schema as $key => $definition) {
            if (is_array($definition) && isset($definition['type'])) {
                $properties[$key] = $definition;
            } elseif (is_string($definition)) {
                $properties[$key] = ['type' => $definition];
            }
        }

        return $properties;
    }

    private function getSchemaType(string $rule): string
    {
        if (str_contains($rule, 'string') || $this->isFileRule($rule)) {
            return 'string';
        }
        if (str_contains($rule, 'integer')) {
            return 'integer';
        }
        if (str_contains($rule, 'numeric') || str_contains($rule, 'decimal')) {
            return 'number';
        }
        if (str_contains($rule, 'boolean')) {
            return 'boolean';
        }
        if (str_contains($rule, 'array')) {
            return 'array';
        }

        return 'string';
    }

    private function isFileRule(string $rule): bool
    {
        return str_contains($rule, 'file') || str_contains($rule, 'image');
    }

    /**
     * @param array<string, string[]> $rules
     */
    private function hasFileRule(array $rules): bool
    {
        foreach ($rules as $attrRules) {
            foreach ($attrRules as $rule) {
                if ($this->isFileRule($rule)) {
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * @return array<string, mixed[]>
     */
    private function getSecurityRequirement(string $authType): array
    {
        return match ($authType) {
            'bearer', 'sanctum', 'jwt' => ['bearerAuth' => []],
            'basic'                     => ['basicAuth' => []],
            'oauth2'                    => ['oauth2' => []],
            default                     => ['bearerAuth' => []],
        };
    }

    private function buildSecuritySchemes(): void
    {
        $securityType = config('api-lens.open_api.security.type');

        if ($securityType === null) {
            return;
        }

        $schemes = match ($securityType) {
            'bearer' => [
                'bearerAuth' => [
                    'type'   => 'http',
                    'scheme' => 'bearer',
                ],
            ],
            'basic' => [
                'basicAuth' => [
                    'type'   => 'http',
                    'scheme' => 'basic',
                ],
            ],
            'apikey' => [
                'apiKeyAuth' => [
                    'type' => 'apiKey',
                    'name' => config('api-lens.open_api.security.name', 'api_key'),
                    'in'   => config('api-lens.open_api.security.position', 'header'),
                ],
            ],
            'jwt' => [
                'bearerAuth' => [
                    'type'         => 'http',
                    'scheme'       => 'bearer',
                    'bearerFormat' => 'JWT',
                ],
            ],
            'oauth2' => [
                'oauth2' => [
                    'type'  => 'oauth2',
                    'flows' => [
                        'authorizationCode' => [
                            'authorizationUrl' => config('api-lens.open_api.security.authorization_url', '/oauth/authorize'),
                            'tokenUrl'         => config('api-lens.open_api.security.token_url', '/oauth/token'),
                            'scopes'           => config('api-lens.open_api.security.scopes', []),
                        ],
                    ],
                ],
            ],
            default => [],
        };

        if (!empty($schemes)) {
            $this->openApi['components']['securitySchemes'] = $schemes;
            $this->openApi['security'] = [array_map(fn() => [], $schemes)];
        }
    }
}
